[package]
name = "bucketize"
version = "0.1.0"
authors = ["Mohammed Lazhari <mohammed.lazhari@frontiercargroup.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
